num1 = int(input("Enter Number 1: "))
num2 = int(input("Enter Number 2: "))
num3 = int(input("Enter Number 3: "))
num4 = int(input("Enter Number 4: "))
num5 = int(input("Enter Number 5: "))
num6 = int(input("Enter Number 6: "))
num7 = int(input("Enter Number 7: "))
num8 = int(input("Enter Number 8: "))

allNumbers = set()
allNumbers.add(num1)
allNumbers.add(num2)
allNumbers.add(num3)
allNumbers.add(num4)
allNumbers.add(num5)
allNumbers.add(num6)
allNumbers.add(num7)
allNumbers.add(num8)

print(allNumbers)